/*********** CREDIT_CARDS_ARCHIVE table ***********/

-- Create CREDIT_CARDS_ALL table
CREATE TABLE CREDIT_CARDS_ALL (
    CC_SUR INTEGER,
    CC_NUMBER VARCHAR2(255 BYTE) PRIMARY KEY,
    CC_NUMBER_MASKED VARCHAR2(255 BYTE),
    CC_BAL VARCHAR2(100 BYTE),
    CC_LIMIT VARCHAR2(100 BYTE),
    CC_OPEN_DATE DATE,
    ACCT_OPEN_DATE VARCHAR2(255 BYTE),
    EMP_NAME VARCHAR2(255 BYTE),
    EMP_EMAIL VARCHAR2(255 BYTE),
    EMP_DEPT_NAME VARCHAR2(100 BYTE) 
);

/*********** CREDIT_CARDS_ARCHIVE table ***********/

-- Create CREDIT_CARDS_ARCHIVE table
CREATE TABLE CREDIT_CARDS_ARCHIVE (
    CC_SUR INTEGER,
    CC_NUMBER VARCHAR2(255 BYTE) PRIMARY KEY,
    CC_NUMBER_MASKED VARCHAR2(255 BYTE),
    CC_BAL VARCHAR2(100 BYTE),
    CC_LIMIT VARCHAR2(100 BYTE),
    CC_OPEN_DATE DATE,
    ACCT_OPEN_DATE VARCHAR2(255 BYTE),
    EMP_NAME VARCHAR2(255 BYTE),
    EMP_EMAIL VARCHAR2(255 BYTE),
    EMP_DEPT_NAME VARCHAR2(100 BYTE) 
);

/*********** CREDIT_CARDS_CURRENT table ***********/

-- Create CREDIT_CARDS_CURRENT table
CREATE TABLE CREDIT_CARDS_CURRENT (
    CC_SUR INTEGER,
    CC_NUMBER VARCHAR2(255 BYTE) PRIMARY KEY,
    CC_NUMBER_MASKED VARCHAR2(255 BYTE),
    CC_BAL VARCHAR2(100 BYTE),
    CC_LIMIT VARCHAR2(100 BYTE),
    CC_OPEN_DATE DATE,
    ACCT_OPEN_DATE VARCHAR2(255 BYTE),
    EMP_NAME VARCHAR2(255 BYTE),
    EMP_EMAIL VARCHAR2(255 BYTE),
    EMP_DEPT_NAME VARCHAR2(100 BYTE) 
);

commit
